techmovie/easy-upload

- src/config.yaml
这是不额外填写字段的类型所对应的id
电影，name
剧集，series_enname
记录，doc_enname
综艺，show_enname
其他需要额外填写的：
动漫，anime_enname
```
<tbody id="title-block-beginner" style="display: table-row-group;"><tr><td class="rowhead nowrap" align="right" valign="top">英文名</td><td class="rowfollow" align="left" valign="top"><input class="mustfill fill" style="width: 400px;" id="anime_enname" name="anime_enname" type="text"><br><font class="medium" color="red">请填写 罗马音名 或 英文译名</font></td></tr>
<tr><td class="rowhead nowrap" align="right" valign="top">集数/集别<br>卷数/张数</td><td class="rowfollow" align="left" valign="top"><input class="fill" style="width: 400px;" id="anime_serinum" name="anime_serinum" type="text"><br><font class="medium" color="red">注明OVA/OAD/MOVIE；合集：TV 01-XX Fin +SP/OVA/MOVIE 或 Vol.1-Vol.X Fin</font></td></tr> …
```
> 添加南洋，还差标题未自动填写

- scripts/helper.js
I was banned on bootcss.com just  by trying to install the script few times in a row.
On the original host there is no such limitations.
> Changed jquery link to  https://cdn.staticfile.org

- src/source/kg.js
> Removes 'Remux' search on KG

- src/config/PTP.yaml
- src/source/ptp.js
> feat: 完善PTP版本标签

- src/const.js
- src/site-dom/button-function.js
- src/source/ptp.js
- src/target/its.js
- 之前: `comparisonImgs: [imgUrl]`
- 现在：`comparisons: [ { title, imgs: [imgUrl] }, .. ]`
这个title很重要.
还有一部分未改完
> feat: comparisonImgs改为comparisons

- src/source/ptp.js
> fix: 修复PTP图片带链接

- src/source/ptp.js
> fix: PTP comparison支持大小写

- src/source/ptp.js
种子ID: 86888
其实是需要修复getBDInfoOrMediaInfo的，先用一个if吧
> fix: 处理PTP mediainfo得不到的情况

- src/const.js
- src/source/ptp.js
1. originalDescription是没有进行修改过的description, 目标站点可以根据自己的需求直接使用未修改的description
2. comparisons增加reason, e.g. ptp id 585231
> fix: PTP增加originalDescription

- src/config/PTP.yaml
- src/const.js
- src/source/ptp.js
1. mediaInfoArray 支持 VTS_10_0.IFO: ptp 704140
2. 增加 mediaInfos: 方便目标站使用.
3. 支持 `[comparison]` 大小写
4. Edition Tags增加 `Two-Disc Set`
> fix: ptp多个修复

- src/config/PTP.yaml
- src/source/ptp.js
Also sort editionTags in alphabet order
> fix: PTP edition tags remove freeleech

- src/target/gpw.js
> fix: 自动激活GPW自带验证

- src/target/gpw.js
[前面](https://github.com/techmovie/easy-upload/pull/119/files#diff-25eef395cc12c06b7abc1a9cd4ba51fd765dff20769f3d5e3268399c727d4bd1L151)改错了, textarea下面 `change`事件是自动填充, `input`事件是验证
> fix: GPW mediainfo autofill

- src/target/gpw.js
> fix: GPW processing validation

- src/target/index.ts
> fix(frds): use originalDescription that can keep comparison

- src/source/nexusphp.ts
> feat(frds): support get doubaninfo

- src/target/index.ts
因为这个用的是 originalDescription 所以要单独改
> fix(ptp2frds): add reg for old img bbcode

- src/source/ptp.ts
- src/target/bhd.ts
- src/target/index.ts
torrents.php?id=36695&torrentid=1043927
之前的代码会多出一层img标签
> fix(ptp): problem with standard bbcode img

- src/source/bhd.ts
https://github.com/techmovie/easy-upload/issues/209
主要是没有imdb tt开头得到tags了
> fix(bhd): get imdb url

- src/source/nexusphp.ts
主要处理comparison 转到其他站，一个图一个回车的问题
> fix(frds): comparison to np

- src/components/UploadSiteList.tsx
- src/target/ptp.ts
https://github.com/techmovie/easy-upload/issues/225
> fix(aither): cartoon issue

- src/source/nexusphp.ts
- src/source/ptp.ts
- src/target/index.ts
> feat: some fix and support get tag chinese subtitle from mediainfo

- scripts/helper.js
- src/config/MTV.yaml
- src/target/helper.ts
- src/target/site-operations.ts
简单的填写一些信息。
mtv需要cover img 但是不支持imdb的amzon url 的图，目前我都是用tmdb的(需要手动填写)
tag需要填8个，估摸要写一大堆判断
分辨率和source还没处理
> feat: support upload to mtv

- src/common.ts
- src/source/nexusphp.ts
https://github.com/techmovie/easy-upload/issues/286
> fix: disc info not remove

- src/config/BTSCHOOL.yaml
- src/config/CHDBits.yaml
- src/config/HDArea.yaml
- src/config/HDDolby.yaml
- src/config/HDHome.yaml
- src/config/HDU.yaml
- src/config/HaresClub.yaml
- src/config/PTHome.yaml
- src/config/PTSBAO.yaml
- src/config/PTer.yaml
- src/config/PuTao.yaml
感觉基本所有都有问题，不知道什么时候开始的，没全改，有些不好验证
> fix: some np site name selector error

- src/source/helper.ts
https://github.com/techmovie/easy-upload/issues/296
> fix: torrent download link

- .gitattributes
参考这里 https://github.com/pt-plugins/PT-Plugin-Plus/issues/1981
默认直接装github的应该不太有问题，不清楚自己装git的情况是如何。
目前我遇到的就是Win下的工作文件夹和Linux共享，会提示整体的变动
> feat: add gitattributes
